### ISSUE TITLE
关于单元测试的一些思路

### ISSUE THREAD

**Issue by Skyseaee** [Skyseaee/Java_coursework_8th#5]
## 测试文件的创建
- 创建文件夹以及在对应的文件夹下面创建文件，文件内容可以是一段随机数+随机字母等形式，文件名称用一些组合规则进行规范（非必须）方便后续验证

## 自动化验证：
- 创建一个方法来进行对应的哈希值的检验，验证文件夹对应的文件内容是否是文件夹对应的子文件或子文件夹的哈希以及blob / tree是否正确
- 创建一个方法来进行自动的查询
- 创建一个方法来进行commit的提交
- 创建一个方法来进行commit的回滚等操作
暂时我的想法就是这样 @keira-hq

**Comment by keira-hq** [comment]
单元测试（模块测试）应该是把每个模块作为一个单独的实体来测试，每个模块完成一个清晰定义的子功能，也就是检验这个子功能是否顺利完成。
我们可以创建多个单元测试，第一个用来检验对应的哈希值，第二个用来检查commit文件中保存的信息是否正确等，把以上的这些放方法分到不同的单元测试中去。

**Comment by Skyseaee** [comment]
**第一个检测对应的哈希值**
使用Junit的断言方法来进行测试
- 在@Before中实例化DFSFolder对象，创建文件夹以及一些子文件和子文件夹等
- 在@Test中使用断言的方式验证查找的功能，使用`assertEquals(expected, actual)` （还没研究完不知道可行性如何）查看
- 在@After中释放资源

**第二个Commit功能的单元测试**
- 编写一些修改文件的方法
- 在@Test中提交调用修改文件的方法进行几次不同的commit，通过断言判断结果是否正确
（学了一会Junit之后的一些思路，具体实现还没有确定不太懂这个模块还在尝试中hhh @keira-hq ）
